
version: 2
jobs:
    build:
        docker:
            - image: koppor/texlive
        steps:
            - run:
                name: Git settings
                command: |
                    git config --global user.email 'fujiisoup@gmail.com'
                    git config --global user.name 'fujiisoup'
            - checkout
            - run:
                name: Generating current version
                command: |
                    cd doc
                    make
                    cd ../
    deploy:
        docker:
            - image: koppor/texlive
        steps:
            - run:
                name: Git settings
                command: |
                    git config --global user.email 'fujiisoup@gmail.com'
                    git config --global user.name 'fujiisoup'
            - checkout
            - run:
                name: Generating current version
                command: |
                    cd doc
                    make
                    cd ../
            - run:
                name: Commit to repository
                command: |
                    git checkout release-pdf
                    cp doc/manual.pdf manual.pdf
                    git add manual.pdf
                    git commit -m "[CircleCI] Generate PDF @$(date +'%Y/%m/%d %I:%M') [ci skip]"
                    git push origin release-pdf

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
